### ISSUE TITLE
VibranceGUI is not working on CS:GO help me! :((

### ISSUE THREAD

**Issue by M3dik** [juvlarN/vibranceGUI#43] opened 2017-06-30 12:25 UTC
So 2months ago I downloaded the VibranceGUI and I was like: ,,Yes new VibranceGUI!"
So I put the Counter Strike-Global Offensive there and max it to 100% And it wasn't working :(
But on other games (for example H1Z1 King Of The Kill) it's working 100% good

PLEASE juvlarN HELP ME! :(((

**Comment by juvlarN** [comment] 2017-06-30 12:26
Duplicate of this issue: https://github.com/juvlarN/vibranceGUI/issues/35

**Closed by juvlarN** 2017-06-30 12:26 UTC
