### ISSUE TITLE
Hangs Windows Explorer on Startup

### ISSUE THREAD

**Issue by harrymilne** [juvlarN/vibranceGUI#28] opened 2016-12-23 17:20 UTC
When I initially log into Windows 10 vibranceGUI seems to make Windows Explorer hang so I can't click anything, however, it does respond to me hovering over the elements (highlights on hover).

This affects the Start Menu and Taskbar.

**Comment by juvlarN** [comment] 2016-12-23 17:21
Hi @harrymilne,

this is apparently caused by a bug in Microsofts .NET Framework.

The issue has already been addressed in the beta versions.
Try the newest beta version on my twitter (@juvlarN). The version fixes this issue.

**Closed by juvlarN** 2016-12-23 17:21 UTC
